import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import NavigationBar from "@/components/navigation/navigation-bar";
import { getSession } from "@/lib/auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
	title: "Form Management with Next.js App Router",
	description: "Generated by create next app",
};

async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getSession();

	return (
		<html lang="en">
			<body className={cn("min-h-screen", inter.variable)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<NavigationBar session={session} />
					<div className="p-10">{children}</div>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}

export default RootLayout;
